// <auto-generated />
namespace BlogManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ContentParagraphs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContentParagraphs));
        
        string IMigrationMetadata.Id
        {
            get { return "201808230911476_ContentParagraphs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
